sudo: false
language: python
os:
  - linux
  - osx
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.5-dev
  - nightly
matrix:
  allow_failures:
    - os: osx
    - python: 3.5-dev
    - python: nightly


before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  - pip
  - directories:
    - $HOME/.cache/pip

before_install:
  - pip install --upgrade git+git://github.com/andras-tim/pytest-pylint
  - pip install --upgrade pip setuptools wheel coveralls codacy-coverage

install:
  - python setup.py install

script:
  - python setup.py test --pytest-args '-vv --full-trace --cov=octoconf'

after_success:
  - coveralls
  - coverage xml && python-codacy-coverage -r coverage.xml
