USED_CONFIG: ProductionConfig

# This config YAML has been copied from a Flask based project for make real example.
# FYI: The unit tests uses this file, so this is a lieve, and working config.
#
# There are 11 nodes on the top level, so there are 11 config profile.


# This config profile is the base of other profiles in this YAML
DefaultConfig:
  DebugId: Default
  App:
    UTF8_VALUE: 'Több hűtőházból kértünk színhúst'
    VALUE_WITH_VARIABLE: $BASEDIR/my_res

  Flask:
    SERVER_NAME: 0.0.0.0:8000
    STATIC_FOLDER: /test
    DEBUG: False
    TESTING: False

  SqlAlchemy:
    SQLALCHEMY_DATABASE_URI: sqlite://$BASEDIR/app.sqlite


# This profile is only an alias for the "ProductionConfig"
UserConfig:
  Base: ProductionConfig


# This profile inherites all properties from the "DefaultConfig"
ProductionConfig:
  Base: DefaultConfig
  DebugId: Production

  SqlAlchemy:
    SQLALCHEMY_DATABASE_URI: mysql+mysqlconnector://tasks:a@localhost/tasks


DevelopmentConfig:
  Base: DefaultConfig
  DebugId: Development

  Flask:
    DEBUG: True


TestingConfig:
  Base: DefaultConfig
  DebugId: Testing

  Flask:
    TESTING: True


DependencyTopConfig:
  Base: DependencyMiddleConfig
  DebugId: DependencyTop

  DependencyLevel:
    1: Top


DependencyMiddleConfig:
  Base: DependencyBottomConfig
  DebugId: DependencyMiddle

  DependencyLevel:
    1: Middle
    2: Middle


DependencyBottomConfig:
  DebugId: DependencyBottom

  DependencyLevel:
    1: Bottom
    2: Bottom
    3: Bottom


MinimalCircularConfig:
  Base: MinimalCircularConfig
  DebugId: MinimalCircular


MultiCircularConfigTop:
  Base: MultiCircularConfigMiddle
  DebugId: MultiCircularTop


MultiCircularConfigMiddle:
  Base: MultiCircularConfigBottom
  DebugId: MultiCircularBottom


MultiCircularConfigBottom:
  Base: MultiCircularConfigTop
  DebugId: MultiCircularBottom
